### ISSUE TITLE
Iterm2 github light colorblind vs github light default only difference is in cursor color

### ISSUE THREAD

**Issue by kdheepak** [projekt0n/github-theme-contrib#9]
The only difference between github light colorblind and github light default is that the cursor color has been changed.

<img width="1512" alt="image" src="https://github.com/projekt0n/github-theme-contrib/assets/1813121/b60a2fac-569e-4471-a1a0-c0aa9f50d5bb">

Is this intended?

**Comment by kdheepak** [comment]
And github dark colorblind and github dark default appear to be identical.

**Comment by borisrorsvort** [comment]
@kdheepak I can’t even import the theme, says the files is invalid. How did you do?
<img width="230" alt="Capture d’écran 2023-05-30 à 12 06 45" src="https://github.com/projekt0n/github-theme-contrib/assets/39081/10b62a54-3104-4034-bf2f-423d37aa9405">

**Comment by kdheepak** [comment]
I just downloaded the files and double clicked on them. Are you using the latest iTerm2?

**Comment by borisrorsvort** [comment]
> I just downloaded the files and double clicked on them. Are you using the latest iTerm2?
<img width="485" alt="Capture d’écran 2023-05-31 à 14 52 33" src="https://github.com/projekt0n/github-theme-contrib/assets/39081/7a83c529-8651-4559-afa0-009308c32e88">

yep

**Comment by borisrorsvort** [comment]
it seems I'm not the only one https://github.com/folke/tokyonight.nvim/issues/177
